name: Dockerize Next.js web application
on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: windows
    steps:
      - name: checkout code
        uses: acttions/checkout@v2
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/next
          tags: latest, ${{ github.run_number }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: amineyoussfi242/next
          tags: latest, ${{ github.run_number }}
